//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Behavioral_Observation
    {
        public int Behavioral_Observation_Answer_ID { get; set; }
        public int CaseHistory_ID { get; set; }
        public string Aggressive { get; set; }
        public string Restlessness { get; set; }
        public string Impulsivity { get; set; }
        public string Distractibility { get; set; }
        public string Destructive { get; set; }
        public string Hyper_Active { get; set; }
        public string Tantrum { get; set; }
        public string Self_Stimulation { get; set; }
        public string Shyness { get; set; }
        public string Complain { get; set; }
        public string Dependence { get; set; }
        public string Low_Self_Image { get; set; }
        public string Add_ { get; set; }
        public string Short_Attention_Span { get; set; }
        public string Poor_Motivation { get; set; }
        public string Isolation_ { get; set; }
        public string Withdrawn { get; set; }
        public string Asocial { get; set; }
    
        public virtual Case_History Case_History { get; set; }
    }
}
