//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Create_Teacher
    {
        public int Teacher_ID { get; set; }
        public string Teacher_Picture { get; set; }
        public string Teacher_Name { get; set; }
        public string Gender { get; set; }
        public string NIC { get; set; }
        public string Contact { get; set; }

        public System.DateTime Date_of_Birth { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Status { get; set; }
        public int User_ID { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
    
        public virtual User User { get; set; }
    }
}
