//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Developmental_History
    {
        public int Developmental_History_ID { get; set; }
        public int Speach_Case_History_ID { get; set; }
        public string Use_Single_Word { get; set; }
        public string Combine_Word { get; set; }
        public string Name_Single_Object { get; set; }
        public string Use_Simple_Sentence { get; set; }
        public string Engage_Conversation { get; set; }
        public string Consistently_Sound { get; set; }
        public string Difficulty_Hearing_Speech { get; set; }
        public string HearingTest_Where_When { get; set; }
        public string Diificult_Understand_Speech { get; set; }
        public string SpecificSounds_Incoorectly { get; set; }
        public string Difficulty_Understanding_Direction { get; set; }
        public string Difficulty_PlayActivities { get; set; }
        public string Engage_Excussive_Repetition_Word { get; set; }
        public string Feeding_Problem { get; set; }
    
        public virtual Speach_Case_History Speach_Case_History { get; set; }
    }
}
