//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_History
    {
        public int Education_History_ID { get; set; }
        public int CaseHistory_ID { get; set; }
        public string Name_of_School { get; set; }
        public string Age_at_First_Admission { get; set; }
        public string Performance { get; set; }
        public string Duration { get; set; }
        public string Reason_for_Withdrawal { get; set; }
    
        public virtual Case_History Case_History { get; set; }
    }
}
