//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expressive_Langauage
    {
        public int Expressive_Langauage_ID { get; set; }
        public int Speach_Case_History_ID { get; set; }
        public string Babble { get; set; }
        public string First_Word { get; set; }
        public string Combine_2_Word { get; set; }
        public string Complete_Sentence { get; set; }
        public string Gestures { get; set; }
        public string Phrases { get; set; }
        public string Sing_Language { get; set; }
        public string Sentence { get; set; }
        public string Words { get; set; }
        public string Conversation_Ex_Text { get; set; }
        public string When_Did_Concerned_Child_Speech { get; set; }
        public string Caused_Your_Child_Difficulty { get; set; }
        public string Worse_Better_Overtime { get; set; }
        public string Self_Consious_Speech_Langauge { get; set; }
        public string Speech_Language_Hearing_Family { get; set; }
        public string Professionals_Seen_Child { get; set; }
    
        public virtual Speach_Case_History Speach_Case_History { get; set; }
    }
}
