//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family_History
    {
        public int Family_History_ID { get; set; }
        public int CaseHistory_ID { get; set; }
        public string Father_Name { get; set; }
        public int Father_Age { get; set; }
        public string Father_Education { get; set; }
        public string Father_Profession { get; set; }
        public string Father_Financial_Status { get; set; }
        public string Father_General_Health { get; set; }
        public string Father_Blood_Group { get; set; }
        public string Year_of_Marriage { get; set; }
        public Nullable<int> Father_Age_at_the_time_of_Child_Birth { get; set; }
        public string Father_Paternal_Relationship { get; set; }
        public string Father_Family_System { get; set; }
        public string Mother_Name { get; set; }
        public Nullable<int> Mother_Age { get; set; }
        public string Mother_Education { get; set; }
        public string Mother_Profession { get; set; }
        public string Mother_Financial_Status { get; set; }
        public string Mother_General_Health { get; set; }
        public string Mother_Blood_Group { get; set; }
        public Nullable<int> Mother_Age_at_the_time_of_Child_Birth { get; set; }
        public string Mother_Paternal_Relationship { get; set; }
        public string Mother_Family_System { get; set; }
    
        public virtual Case_History Case_History { get; set; }
    }
}
