//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class General_Information
    {
        public int General_Information_ID { get; set; }
        public int Speach_Case_History_ID { get; set; }
        public System.DateTime Today_Date { get; set; }
        public string Child_Primary_Language { get; set; }
        public string Parent_Primary_Language { get; set; }
        public string Live_With_Both_Parents { get; set; }
        public string Child_Primary_Caregiver { get; set; }
        public string Child_Primary_Caregiver_Language { get; set; }
    
        public virtual Speach_Case_History Speach_Case_History { get; set; }
    }
}
