//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Particulars_of_Sibling
    {
        public int Particulars_of_Sibling_ID { get; set; }
        public int CaseHistory_ID { get; set; }
        public int Number_of_Siblings { get; set; }
        public Nullable<int> Child_Order { get; set; }
        public string Any_Disability { get; set; }
    
        public virtual Case_History Case_History { get; set; }
    }
}
