//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Psycho_Social_Factors
    {
        public int Psycho_Social_Factors_ID { get; set; }
        public int CaseHistory_ID { get; set; }
        public string Friends_Attitude { get; set; }
        public string Sibling_Relationship { get; set; }
        public string HomeAndParent_Attitude { get; set; }
        public string HobbiesAndInterest { get; set; }
    
        public virtual Case_History Case_History { get; set; }
    }
}
