//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QRSCS_DatabaseEntities : DbContext
    {
        public QRSCS_DatabaseEntities()
            : base("name=QRSCS_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Case_History> Case_History { get; set; }
        public virtual DbSet<Developmental_History> Developmental_History { get; set; }
        public virtual DbSet<Expressive_Langauage> Expressive_Langauage { get; set; }
        public virtual DbSet<General_Information> General_Information { get; set; }
        public virtual DbSet<Receptive_langauge> Receptive_langauge { get; set; }
        public virtual DbSet<Speach_and_Langauge> Speach_and_Langauge { get; set; }
        public virtual DbSet<Speach_Case_History> Speach_Case_History { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<New_Admission> New_Admission { get; set; }
        public virtual DbSet<Behavioral_Observation> Behavioral_Observation { get; set; }
        public virtual DbSet<Conclusion> Conclusions { get; set; }
        public virtual DbSet<Development_History> Development_History { get; set; }
        public virtual DbSet<Education_History> Education_History { get; set; }
        public virtual DbSet<Family_History> Family_History { get; set; }
        public virtual DbSet<Medical_History> Medical_History { get; set; }
        public virtual DbSet<Particulars_of_Sibling> Particulars_of_Sibling { get; set; }
        public virtual DbSet<Post_Natal> Post_Natal { get; set; }
        public virtual DbSet<Psycho_Social_Factors> Psycho_Social_Factors { get; set; }
        public virtual DbSet<Recommendation> Recommendations { get; set; }
        public virtual DbSet<Speech_Therapy_Assessment> Speech_Therapy_Assessment { get; set; }
        public virtual DbSet<Audiology_Assessment> Audiology_Assessment { get; set; }
        public virtual DbSet<Create_Teacher> Create_Teacher { get; set; }
    }
}
