//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receptive_langauge
    {
        public int Receptive_langauge_ID { get; set; }
        public int Speach_Case_History_ID { get; set; }
        public string Single_Words { get; set; }
        public string Yes_No_Questions { get; set; }
        public string Sentences { get; set; }
        public string WH_Questions { get; set; }
        public string Routine_Questions { get; set; }
        public string Conversation_Text { get; set; }
    
        public virtual Speach_Case_History Speach_Case_History { get; set; }
    }
}
