//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speach_and_Langauge
    {
        public int Speach_and_Langauge_ID { get; set; }
        public int Speach_Case_History_ID { get; set; }
        public string Speech_Text { get; set; }
    
        public virtual Speach_Case_History Speach_Case_History { get; set; }
    }
}
